-- Core sync/bootstrap parity migration (v8)
-- Apply after v7 release hardening migration.

-- Canonical metadata columns for mutable tables.
alter table if exists public.transactions add column if not exists updated_at timestamptz default now();
alter table if exists public.transactions add column if not exists sync_state text not null default 'LOCAL_ONLY';
alter table if exists public.transactions add column if not exists record_source text not null default 'SMS';
alter table if exists public.transactions add column if not exists deleted_at timestamptz;
alter table if exists public.transactions add column if not exists revision bigint not null default 0;

alter table if exists public.tasks add column if not exists updated_at timestamptz default now();
alter table if exists public.tasks add column if not exists sync_state text not null default 'LOCAL_ONLY';
alter table if exists public.tasks add column if not exists record_source text not null default 'MANUAL';
alter table if exists public.tasks add column if not exists deleted_at timestamptz;
alter table if exists public.tasks add column if not exists revision bigint not null default 0;

alter table if exists public.events add column if not exists updated_at timestamptz default now();
alter table if exists public.events add column if not exists sync_state text not null default 'LOCAL_ONLY';
alter table if exists public.events add column if not exists record_source text not null default 'MANUAL';
alter table if exists public.events add column if not exists deleted_at timestamptz;
alter table if exists public.events add column if not exists revision bigint not null default 0;

alter table if exists public.budgets add column if not exists updated_at timestamptz default now();
alter table if exists public.budgets add column if not exists sync_state text not null default 'LOCAL_ONLY';
alter table if exists public.budgets add column if not exists record_source text not null default 'MANUAL';
alter table if exists public.budgets add column if not exists deleted_at timestamptz;
alter table if exists public.budgets add column if not exists revision bigint not null default 0;

alter table if exists public.incomes add column if not exists created_at timestamptz default now();
alter table if exists public.incomes add column if not exists updated_at timestamptz default now();
alter table if exists public.incomes add column if not exists sync_state text not null default 'LOCAL_ONLY';
alter table if exists public.incomes add column if not exists record_source text not null default 'MANUAL';
alter table if exists public.incomes add column if not exists deleted_at timestamptz;
alter table if exists public.incomes add column if not exists revision bigint not null default 0;

alter table if exists public.recurring_rules add column if not exists updated_at timestamptz default now();
alter table if exists public.recurring_rules add column if not exists sync_state text not null default 'LOCAL_ONLY';
alter table if exists public.recurring_rules add column if not exists record_source text not null default 'RECURRING';
alter table if exists public.recurring_rules add column if not exists deleted_at timestamptz;
alter table if exists public.recurring_rules add column if not exists revision bigint not null default 0;

-- New sync and intelligence support tables.
create table if not exists public.sync_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  job_type text not null,
  entity_type text not null,
  entity_id text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'QUEUED',
  attempt_count integer not null default 0,
  last_error text,
  next_run_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_sync_jobs_user_status on public.sync_jobs(user_id, status, next_run_at);

create table if not exists public.import_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  raw_message text not null,
  mpesa_code text,
  amount numeric,
  merchant text,
  outcome text not null,
  failure_reason text,
  imported_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_import_audit_user_time on public.import_audit(user_id, imported_at desc);

create table if not exists public.assistant_conversations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  sync_state text not null default 'LOCAL_ONLY',
  record_source text not null default 'ASSISTANT',
  deleted_at timestamptz,
  revision bigint not null default 0
);

create table if not exists public.assistant_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  conversation_id bigint not null references public.assistant_conversations(id) on delete cascade,
  role text not null,
  content text not null,
  action_payload jsonb,
  is_preview boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  sync_state text not null default 'LOCAL_ONLY',
  record_source text not null default 'ASSISTANT',
  deleted_at timestamptz,
  revision bigint not null default 0
);

create table if not exists public.insight_cards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null,
  title text not null,
  body text not null,
  confidence numeric,
  is_ai_generated boolean not null default false,
  fresh_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  sync_state text not null default 'LOCAL_ONLY',
  record_source text not null default 'SYSTEM',
  deleted_at timestamptz,
  revision bigint not null default 0
);

create table if not exists public.review_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  period_start timestamptz not null,
  period_end timestamptz not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  sync_state text not null default 'LOCAL_ONLY',
  record_source text not null default 'SYSTEM',
  deleted_at timestamptz,
  revision bigint not null default 0
);

create table if not exists public.app_update_info (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  version_code bigint not null,
  version_name text,
  is_required boolean not null default false,
  download_url text,
  checksum_sha256 text,
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sync_jobs enable row level security;
alter table public.import_audit enable row level security;
alter table public.assistant_conversations enable row level security;
alter table public.assistant_messages enable row level security;
alter table public.insight_cards enable row level security;
alter table public.review_snapshots enable row level security;
alter table public.app_update_info enable row level security;

create policy if not exists sync_jobs_select on public.sync_jobs for select using (auth.uid() = user_id);
create policy if not exists sync_jobs_insert on public.sync_jobs for insert with check (auth.uid() = user_id);
create policy if not exists sync_jobs_update on public.sync_jobs for update using (auth.uid() = user_id);
create policy if not exists sync_jobs_delete on public.sync_jobs for delete using (auth.uid() = user_id);

create policy if not exists import_audit_select on public.import_audit for select using (auth.uid() = user_id);
create policy if not exists import_audit_insert on public.import_audit for insert with check (auth.uid() = user_id);
create policy if not exists import_audit_update on public.import_audit for update using (auth.uid() = user_id);
create policy if not exists import_audit_delete on public.import_audit for delete using (auth.uid() = user_id);

create policy if not exists assistant_conversations_select on public.assistant_conversations for select using (auth.uid() = user_id);
create policy if not exists assistant_conversations_insert on public.assistant_conversations for insert with check (auth.uid() = user_id);
create policy if not exists assistant_conversations_update on public.assistant_conversations for update using (auth.uid() = user_id);
create policy if not exists assistant_conversations_delete on public.assistant_conversations for delete using (auth.uid() = user_id);

create policy if not exists assistant_messages_select on public.assistant_messages for select using (auth.uid() = user_id);
create policy if not exists assistant_messages_insert on public.assistant_messages for insert with check (auth.uid() = user_id);
create policy if not exists assistant_messages_update on public.assistant_messages for update using (auth.uid() = user_id);
create policy if not exists assistant_messages_delete on public.assistant_messages for delete using (auth.uid() = user_id);

create policy if not exists insight_cards_select on public.insight_cards for select using (auth.uid() = user_id);
create policy if not exists insight_cards_insert on public.insight_cards for insert with check (auth.uid() = user_id);
create policy if not exists insight_cards_update on public.insight_cards for update using (auth.uid() = user_id);
create policy if not exists insight_cards_delete on public.insight_cards for delete using (auth.uid() = user_id);

create policy if not exists review_snapshots_select on public.review_snapshots for select using (auth.uid() = user_id);
create policy if not exists review_snapshots_insert on public.review_snapshots for insert with check (auth.uid() = user_id);
create policy if not exists review_snapshots_update on public.review_snapshots for update using (auth.uid() = user_id);
create policy if not exists review_snapshots_delete on public.review_snapshots for delete using (auth.uid() = user_id);

create policy if not exists app_update_info_select on public.app_update_info for select using (auth.uid() = user_id);
create policy if not exists app_update_info_insert on public.app_update_info for insert with check (auth.uid() = user_id);
create policy if not exists app_update_info_update on public.app_update_info for update using (auth.uid() = user_id);
create policy if not exists app_update_info_delete on public.app_update_info for delete using (auth.uid() = user_id);

